accounts/urls.py
from django.urls import path
from .views import *


app_name = "accounts"


urlpatterns = [
    path("signup/", signupview, name="signup"),
    path("login/", loginview, name="login"),
    path("logout/", logoutview, name="logout"),
    path("loggedout/", loggedoutview, name="loggedout")
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("redit/accounts/", include("accounts.urls")),
    path('redit/', include("pages.urls")),
    # path('accounts/', include("accounts.urls")),
]

if settings.DEBUG :
    urlpatterns += [
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    ]

pages/urls.py
from django.urls import path
from .views import *

app_name = "pages"

urlpatterns = [
    path("home/", homeview, name="home"),
    path("create/", new_postview, name="create"),
    path("js/", jsview, name="javascript")
]

templates/JStutorial.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
        <title>JS tutorial</title>
    {% endblock title %}
</head>
<body>

    {% block content %}
    <h1>This is a h1 tag</h1>

    <button onclick="changeBoxColour()" id="ccbutton">Click Me</button>
    <div id="changeMe"></div>
    {% endblock content %}   
    
    
    {% block js_block %}
        <script src="{% static 'js/index.js' %}"></script>
    {% endblock js_block %}

</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html >
<html>
<head>

    {% block title %}
        <title>A Good Blog</title>
    {% endblock title %}

    {% block main-styling %}
        <link href="{% static 'css/main.css' %}" rel="stylesheet">
    {% endblock main-styling %}

    {% block navcss %}
        <link href="{% static 'css/navbar.css' %}" rel="stylesheet">
    {% endblock navcss %}
    
    {% block sp-styling %}

    {% endblock sp-styling %}
    
    
</head>
<body>

    {% block navbar %}
    <div class="nav-hi">
        {% if user.is_authenticated %}
            <p>Hi, {{ user.username }} !</p>
            <p><a href="{% url 'accounts:logout' %}">Log out</a></p>
        {% else %}
            <p>You are not logged in, <a href="{% url 'accounts:login' %}">Log In</a> or <a href="{% url 'accounts:signup'%}">Sign Up</a>.</p>
        {% endif %}
    </div>   
    {% endblock navbar %}

    
    {% block content %}
    
    {% endblock content %}


    {% block js_block %}
        
    {% endblock js_block %}

</body>
</html>

templates/create.html
{% extends "base.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
        <title>New Post</title>
    {% endblock title %}

    {% block sp-styling %}
        <link href="{% static 'css/create.css' %}" rel="stylesheet">
    {% endblock sp-styling %}
</head>
<body>

    {% block content %}
    {% if user.is_authenticated %}
        <div class="new-post-container">
            <div class="new-post">
                <form method="post">
                    {% csrf_token %}

                    <!-- <input type="hidden" value={{ request.user }} name={{form.user.label}}> -->
                    {{ form.as_p }}
                    
                    <input type="submit" name="draft" value="Save as draft">
                    <input type="submit" name="publish" value="Publish">
                </form>
            </div>
        </div>
    {% else %}
        <p>You should <a href="{% url 'accounts:login' %}">Log In</a> first sucker</p>
    {% endif %}
    {% endblock content %}
    
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

<html>
<head>
    {% block title %}
        <title>Home|Blog</title>
    {% endblock title %}


    

    {% block sp-styling %}
        <link href="{% static 'css/feed.css' %}" rel="stylesheet">
    {% endblock sp-styling %}

</head>
<body>
    
    {% block content %}

    
    
    <div class="posts-list">
        {% for post in rposts %}
            <div class="post-block">
                <h1>{{ post.title }}</h1>
                <h3>Published on {{ post.date_published }}</h3>
                <p>By {{ post.user }}</p>
                <p>{{ post.text }}</p>
                <hr>
            </div>
        {% endfor %}
    </div>
    {% endblock content %}

</body>

</html>

templates/loggedout.html
{% extends "base.html" %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    
    {% block title %}
        <title>Logging you out..</title>
    {% endblock title %}

    
    {% block navcss %}
    {% endblock navcss %}
    
    {% block sp-styling %}
        <link href="{% static 'css/authstyle.css' %}" rel="stylesheet">
    {% endblock sp-styling %}
    
</head>
<body>
    {% block navbar %}
    {% endblock navbar %}

    {% block content %}
    {% endblock content %}
</body>
</html>

templates/login.html
{% extends "base.html" %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    
    {% block title %}
        <title>Log In|Redit</title>
    {% endblock title %}

    
    {% block navcss %}
    {% endblock navcss %}
    
    {% block sp-styling %}
        <link href="{% static 'css/authstyle.css' %}" rel="stylesheet">
    {% endblock sp-styling %}
    
</head>
<body>
    {% block navbar %}
    {% endblock navbar %}

    {% block content %}
        <div class="signup-box">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                {{ msg }}
                <button type="submit">Log In</button>
            </form>
        </div>
    {% endblock content %}
</body>
</html>

templates/logout.html
{% extends "base.html" %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    
    {% block title %}
        <title>Log Out|Redit</title>
    {% endblock title %}

    
    {% block navcss %}
    {% endblock navcss %}
    
    {% block sp-styling %}
        <link href="{% static 'css/authstyle.css' %}" rel="stylesheet">
    {% endblock sp-styling %}
    
</head>
<body>
    {% block navbar %}
    {% endblock navbar %}

    {% block content %}
        <div class="signup-box">
            <h5>Are you sure you want to log out?</h5>
            <a href="{% url 'accounts:loggedout' %}">
                <button>Log Out</button>
            </a>
            
            <a href="{% url 'pages:home' %}">
                <button>No!</button>
            </a>
        </div>
    {% endblock content %}
</body>
</html>

templates/signup.html
{% extends "base.html" %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    
    {% block title %}
        <title>Sign Up|Redit</title>
    {% endblock title %}

    
    {% block navcss %}
    {% endblock navcss %}
    
    {% block sp-styling %}
        <link href="{% static 'css/authstyle.css' %}" rel="stylesheet">
    {% endblock sp-styling %}
    
</head>
<body>
    {% block navbar %}
    {% endblock navbar %}

    {% block content %}
        <div class="signup-box">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Sign Up</button>
            </form>
        </div>
    {% endblock content %}
</body>
</html>